name: Build and Test
on:
  push:
    branches:
      - master

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: yarn install, build, and test
        run: |
          yarn install --production=false
          yarn build
          yarn test
        env:
          CI: true
